#!/usr/bin/env node
/**
 * Content pipeline — prebuild/predev par chalta hai:
 *   1. content/posts/*.md  →  src/data/posts.gen.js  (frontmatter + rendered HTML)
 *   2. posts se             →  public/rss.xml
 *   3. posts se             →  public/sitemap.xml  (home + har post, auto lastmod)
 *
 * Usage: node scripts/build-content.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { marked } from "marked";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const POSTS_DIR = path.join(ROOT, "content", "posts");
const OUT_DATA = path.join(ROOT, "src", "data", "posts.gen.js");
const OUT_RSS = path.join(ROOT, "public", "rss.xml");
const OUT_SITEMAP = path.join(ROOT, "public", "sitemap.xml");
const INDEX_HTML = path.join(ROOT, "index.html");

const SITE_URL = "https://abdullah-asim-dev.vercel.app";
const AUTHOR = "Abdullah Bin Asim";

/** Ultra-simple frontmatter parser — sirf key: value pairs support karta hai */
function parseFrontmatter(raw) {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) throw new Error("missing frontmatter block");
  const meta = {};
  for (const line of match[1].split(/\r?\n/)) {
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    meta[key] = value;
  }
  return { meta, body: match[2] };
}

function readingMinutes(md) {
  const words = md.trim().split(/\s+/).length;
  return Math.max(1, Math.round(words / 200));
}

function escapeXml(str = "") {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function loadPosts() {
  if (!fs.existsSync(POSTS_DIR)) return [];
  return fs.readdirSync(POSTS_DIR)
    .filter((f) => f.endsWith(".md"))
    .map((file) => {
      const raw = fs.readFileSync(path.join(POSTS_DIR, file), "utf8");
      const { meta, body } = parseFrontmatter(raw);
      const slug = file.replace(/\.md$/, "");
      for (const req of ["title", "description", "date"]) {
        if (!meta[req]) throw new Error(`${file}: missing "${req}"`);
      }
      return {
        slug,
        title: meta.title,
        description: meta.description,
        date: meta.date,
        tags: (meta.tags || "")
          .split(",")
          .map((t) => t.trim())
          .filter(Boolean),
        readingMinutes: readingMinutes(body),
        html: marked.parse(body, { gfm: true, breaks: false }),
      };
    })
    .sort((a, b) => b.date.localeCompare(a.date));
}

function writePostsModule(posts) {
  const banner = "/* AUTO-GENERATED by scripts/build-content.mjs — DO NOT EDIT.\n   Source: content/posts/*.md */\n";
  const json = JSON.stringify(posts, null, 2);
  fs.writeFileSync(
    OUT_DATA,
    `${banner}export const posts = ${json};\n\nexport function getPost(slug) {\n  return posts.find((p) => p.slug === slug) ?? null;\n}\n`,
  );
}

function writeRss(posts) {
  const items = posts.map((p) => `    <item>
      <title>${escapeXml(p.title)}</title>
      <link>${SITE_URL}/blog/${p.slug}</link>
      <guid isPermaLink="true">${SITE_URL}/blog/${p.slug}</guid>
      <description>${escapeXml(p.description)}</description>
      <pubDate>${new Date(p.date).toUTCString()}</pubDate>
      <author>${escapeXml(AUTHOR)}</author>
${p.tags.map((t) => `      <category>${escapeXml(t)}</category>`).join("\n")}
    </item>`).join("\n");

  fs.writeFileSync(OUT_RSS, `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>${escapeXml(AUTHOR)} — Blog</title>
    <link>${SITE_URL}/</link>
    <atom:link href="${SITE_URL}/rss.xml" rel="self" type="application/rss+xml"/>
    <description>Articles on full-stack development, AI engineering and web performance by ${escapeXml(AUTHOR)}.</description>
    <language>en</language>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
${items}
  </channel>
</rss>
`);
}

function writeSitemap(posts) {
  const today = new Date().toISOString().slice(0, 10);
  const urls = [
    { loc: `${SITE_URL}/`, lastmod: today, changefreq: "weekly", priority: "1.0" },
    ...posts.map((p) => ({
      loc: `${SITE_URL}/blog/${p.slug}`,
      lastmod: p.date,
      changefreq: "monthly",
      priority: "0.6",
    })),
  ];

  fs.writeFileSync(OUT_SITEMAP, `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${u.lastmod}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`).join("\n")}
</urlset>
`);
}

/** index.html ke POSTS-META block mein slug→meta map inject karo (idempotent) */
function writePostsMeta(posts) {
  const meta = Object.fromEntries(
    posts.map((p) => [p.slug, { slug: p.slug, title: p.title, description: p.description, date: p.date }]),
  );
  const block = `<!-- POSTS-META:START auto-generated by scripts/build-content.mjs -->\n    <script>\n      window.__POSTS__ = ${JSON.stringify(meta, null, 6).replace(/\n/g, "\n      ")};\n    </script>\n    <!-- POSTS-META:END -->`;
  const html = fs.readFileSync(INDEX_HTML, "utf8");
  const re = /<!-- POSTS-META:START[\s\S]*?<!-- POSTS-META:END -->/;
  if (!re.test(html)) throw new Error("index.html: POSTS-META markers missing");
  fs.writeFileSync(INDEX_HTML, html.replace(re, block));
}

const posts = loadPosts();
writePostsModule(posts);
writeRss(posts);
writeSitemap(posts);
writePostsMeta(posts);
console.log(`content: ${posts.length} post(s) → posts.gen.js, rss.xml, sitemap.xml, index.html meta`);
