#!/usr/bin/env node
/**
 * Content pipeline — prebuild/predev par chalta hai:
 *   1. content/posts/*.md  →  src/data/posts.gen.js  (frontmatter + rendered HTML)
 *   2. posts se             →  public/rss.xml
 *   3. posts se             →  public/sitemap.xml  (home + har post, auto lastmod)
 *
 * Usage: node scripts/build-content.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { marked } from "marked";
import sharp from "sharp";

import { faqs } from "../src/data/faqs.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const POSTS_DIR = path.join(ROOT, "content", "posts");
const OUT_DATA = path.join(ROOT, "src", "data", "posts.gen.js");
const OUT_RSS = path.join(ROOT, "public", "rss.xml");
const OUT_SITEMAP = path.join(ROOT, "public", "sitemap.xml");
const INDEX_HTML = path.join(ROOT, "index.html");

const SITE_URL = "https://abdullah-asim-dev.vercel.app";
const AUTHOR = "Abdullah Bin Asim";

/** Ultra-simple frontmatter parser — sirf key: value pairs support karta hai */
function parseFrontmatter(raw) {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) throw new Error("missing frontmatter block");
  const meta = {};
  for (const line of match[1].split(/\r?\n/)) {
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    meta[key] = value;
  }
  return { meta, body: match[2] };
}

function readingMinutes(md) {
  const words = md.trim().split(/\s+/).length;
  return Math.max(1, Math.round(words / 200));
}

function escapeXml(str = "") {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function loadPosts() {
  if (!fs.existsSync(POSTS_DIR)) return [];
  return fs.readdirSync(POSTS_DIR)
    .filter((f) => f.endsWith(".md"))
    .map((file) => {
      const raw = fs.readFileSync(path.join(POSTS_DIR, file), "utf8");
      const { meta, body } = parseFrontmatter(raw);
      const slug = file.replace(/\.md$/, "");
      for (const req of ["title", "description", "date"]) {
        if (!meta[req]) throw new Error(`${file}: missing "${req}"`);
      }
      return {
        slug,
        title: meta.title,
        description: meta.description,
        date: meta.date,
        tags: (meta.tags || "")
          .split(",")
          .map((t) => t.trim())
          .filter(Boolean),
        readingMinutes: readingMinutes(body),
        html: marked.parse(body, { gfm: true, breaks: false }),
      };
    })
    .sort((a, b) => b.date.localeCompare(a.date));
}

function writePostsModule(posts) {
  const banner = "/* AUTO-GENERATED by scripts/build-content.mjs — DO NOT EDIT.\n   Source: content/posts/*.md */\n";
  const json = JSON.stringify(posts, null, 2);
  fs.writeFileSync(
    OUT_DATA,
    `${banner}export const posts = ${json};\n\nexport function getPost(slug) {\n  return posts.find((p) => p.slug === slug) ?? null;\n}\n`,
  );
}

function writeRss(posts) {
  const items = posts.map((p) => `    <item>
      <title>${escapeXml(p.title)}</title>
      <link>${SITE_URL}/blog/${p.slug}</link>
      <guid isPermaLink="true">${SITE_URL}/blog/${p.slug}</guid>
      <description>${escapeXml(p.description)}</description>
      <pubDate>${new Date(p.date).toUTCString()}</pubDate>
      <author>${escapeXml(AUTHOR)}</author>
${p.tags.map((t) => `      <category>${escapeXml(t)}</category>`).join("\n")}
    </item>`).join("\n");

  fs.writeFileSync(OUT_RSS, `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>${escapeXml(AUTHOR)} — Blog</title>
    <link>${SITE_URL}/</link>
    <atom:link href="${SITE_URL}/rss.xml" rel="self" type="application/rss+xml"/>
    <description>Articles on full-stack development, AI engineering and web performance by ${escapeXml(AUTHOR)}.</description>
    <language>en</language>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
${items}
  </channel>
</rss>
`);
}

function writeSitemap(posts) {
  const today = new Date().toISOString().slice(0, 10);
  const urls = [
    { loc: `${SITE_URL}/`, lastmod: today, changefreq: "weekly", priority: "1.0" },
    ...posts.map((p) => ({
      loc: `${SITE_URL}/blog/${p.slug}`,
      lastmod: p.date,
      changefreq: "monthly",
      priority: "0.6",
    })),
  ];

  fs.writeFileSync(OUT_SITEMAP, `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${u.lastmod}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`).join("\n")}
</urlset>
`);
}

/** FAQ schema injection — faqs.js se FAQPage JSON-LD generate karo */
function injectFaqSchema() {
  const mainEntity = faqs.map((f) => ({
    "@type": "Question",
    name: f.q,
    acceptedAnswer: {
      "@type": "Answer",
      text: f.a,
    },
  }));
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity,
  };
  const block = `<!-- FAQ-SCHEMA:START auto-generated by scripts/build-content.mjs (src/data/faqs.js) -->
    <script type="application/ld+json">
      ${JSON.stringify(faqSchema, null, 2).replace(/\n/g, "\n      ")}
    </script>
    <!-- FAQ-SCHEMA:END -->
`;
  const html = fs.readFileSync(INDEX_HTML, "utf8");
  const re = /<!-- FAQ-SCHEMA:START[\s\S]*?<!-- FAQ-SCHEMA:END -->/;
  if (!re.test(html)) throw new Error("index.html: FAQ-SCHEMA markers missing");
  fs.writeFileSync(INDEX_HTML, html.replace(re, block));
}

/** Blog JSON-LD schema injection — posts list with blogPost entries */
function injectBlogSchema(posts) {
  const blogPosts = posts.map((p) => ({
    "@type": "BlogPosting",
    headline: p.title,
    description: p.description,
    datePublished: p.date,
    url: `${SITE_URL}/blog/${p.slug}`,
    author: { "@id": `${SITE_URL}/#person` },
    publisher: { "@id": `${SITE_URL}/#person` },
    mainEntityOfPage: `${SITE_URL}/blog/${p.slug}`,
  }));
  const blogSchema = {
    "@context": "https://schema.org",
    "@type": "Blog",
    author: { "@id": `${SITE_URL}/#person` },
    publisher: { "@id": `${SITE_URL}/#person` },
    blogPost: blogPosts,
  };
  const block = `<!-- BLOG-SCHEMA:START auto-generated by scripts/build-content.mjs -->
    <script type="application/ld+json">
      ${JSON.stringify(blogSchema, null, 2).replace(/\n/g, "\n      ")}
    </script>
    <!-- BLOG-SCHEMA:END -->
`;
  const html = fs.readFileSync(INDEX_HTML, "utf8");
  const re = /<!-- BLOG-SCHEMA:START[\s\S]*?<!-- BLOG-SCHEMA:END -->/;
  if (!re.test(html)) throw new Error("index.html: BLOG-SCHEMA markers missing");
  fs.writeFileSync(INDEX_HTML, html.replace(re, block));
}

/** Per-post OG images generate karo — sharp se SVG → JPEG 1200×630 */
function writeOgImages(posts) {
  const ogDir = path.join(ROOT, "public", "blog");
  if (!fs.existsSync(ogDir)) fs.mkdirSync(ogDir, { recursive: true });

  const wrapText = (text, maxWidth) => {
    const words = text.split(" ");
    const lines = [];
    let current = "";
    for (const word of words) {
      const test = current + (current ? " " : "") + word;
      if (test.length > maxWidth && current) {
        lines.push(current);
        current = word;
      } else {
        current = test;
      }
    }
    if (current.trim()) lines.push(current);
    return lines.slice(0, 3);
  };

  posts.forEach((post) => {
    const titleLines = wrapText(post.title, 38);
    const svg = `
<svg width="1200" height="630" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#05060a"/>
      <stop offset="100%" stop-color="#0b1222"/>
    </linearGradient>
  </defs>
  <rect width="1200" height="630" fill="url(#g)"/>
  <text x="60" y="300" font-family="DejaVu Sans, sans-serif" font-size="54" font-weight="bold" fill="#f1f5f9">
    ${titleLines.map((t, i) => `<tspan x="60" dy="${(i * 80) + 80}">${escapeXml(t)}</tspan>`).join("\n")}
  </text>
  <text x="60" y="380" font-family="DejaVu Sans, sans-serif" font-size="26" fill="#67e8f9">${SITE_URL}</text>
</svg>`;

    const imagePath = path.join(ogDir, `${post.slug}.jpg`);
    sharp(Buffer.from(svg))
      .jpeg({ quality: 85 })
      .toFile(imagePath)
      .then(() => console.log(`OG image generated: ${post.slug}.jpg`))
      .catch((e) => console.error(`OG image failed for ${post.slug}:`, e));
  });
}

/** Full prerendered static blog page generate karo */
function writeStaticBlogPages(posts) {
  const blogDir = path.join(ROOT, "public", "blog");
  if (!fs.existsSync(blogDir)) fs.mkdirSync(blogDir, { recursive: true });

  const proseCss = `
    body{margin:0;background:#05060a;color:#e2e8f0;font-family:"Inter",system-ui,sans-serif}
    a{color:#67e8f9;text-decoration:underline;text-underline-offset:3px}
    h1,h2,h3{font-family:var(--font-display);color:#f1f5f9}
    h1{font-size:clamp(32px,5vw,44px);margin:1.5em 0 0.5em}
    h2{font-size:clamp(24px,4vw,32px);margin:1.5em 0 0.8em}
    h3{font-size:clamp(20px,3vw,24px);margin:1.2em 0 0.6em}
    p{line-height:1.75;margin:0.8em 0}
    strong{color:#f8fafc}
    ul,ol{padding-left:1.4em;margin:0.8em 0;display:grid;gap:0.5em}
    ul{list-style:disc}
    ol{list-style:decimal}
    li::marker{color:#22d3ee}
    code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:0.86em;background:rgba(255,255,255,0.06);border:1px solid rgba(255,255,255,0.08);border-radius:6px;padding:0.12em 0.4em;color:#a5f3fc}
    pre{background:rgba(0,0,0,0.5);border:1px solid rgba(255,255,255,0.08);border-radius:14px;padding:1rem 1.15rem;overflow-x:auto}
    blockquote{border-left:3px solid rgba(34,211,238,0.55);padding:0.2em 0 0.2em 1em;color:#94a3b8;font-style:italic}
    table{width:100%;border-collapse:collapse;font-size:0.88rem;overflow-x:auto}
    th,td{border:1px solid rgba(255,255,255,0.09);padding:0.55em 0.8em}
    .prose-content > * + *{margin-top:1.1em}
  `;

  posts.forEach((post) => {
    const slugDir = path.join(blogDir, post.slug);
    if (!fs.existsSync(slugDir)) fs.mkdirSync(slugDir, { recursive: true });

    const canonical = `${SITE_URL}/blog/${post.slug}`;
    const ogImage = `${SITE_URL}/blog/${post.slug}.jpg`;

    const html = `
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="robots" content="index, follow" />
    <meta name="theme-color" content="#05060a" />
    <title>${escapeXml(post.title)} — Abdullah Bin Asim</title>
    <meta name="description" content="${escapeXml(post.description)}" />
    <link rel="canonical" href="${canonical}" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="${canonical}" />
    <meta property="og:title" content="${escapeXml(post.title)}" />
    <meta property="og:description" content="${escapeXml(post.description)}" />
    <meta property="og:image" content="${ogImage}" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:locale" content="en_US" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${escapeXml(post.title)}" />
    <meta name="twitter:description" content="${escapeXml(post.description)}" />
    <meta name="twitter:image" content="${ogImage}" />
    <link rel="stylesheet" href="/fonts.css" />
  </head>
  <body>
    <header style="${proseCss}">
      <nav><a href="/" style="color:#e2e8f0;text-decoration:none;font-weight:bold;">← Back to Portfolio</a></nav>
    </header>
    <main style="${proseCss}">
      <article>
        <h1>${escapeXml(post.title)}</h1>
        <p><time datetime="${post.date}">${new Date(post.date).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" })}</time> · ${post.readingMinutes} min read</p>
        ${post.tags.map((tag) => `<span class="tag">${escapeXml(tag)}</span>`).join(" ")}
        <div class="prose-content">${post.html}</div>
        <p style="margin:2em 0 0;font-size:0.9rem;color:#67e8f9;"><a href="/rss.xml" style="color:#67e8f9;">Subscribe via RSS</a></p>
      </article>
    </main>
    <footer style="${proseCss}"><nav><a href="/" style="color:#e2e8f0;">Home</a> | <a href="/rss.xml" style="color:#67e8f9;">RSS</a></nav></footer>
    <script type="application/ld+json">
      {"@context":"https://schema.org","@type":"BlogPosting","headline":"${escapeXml(post.title)}","description":"${escapeXml(post.description)}","datePublished":"${post.date}","url":"${canonical}","author":{"@id":"${SITE_URL}/#person"},"publisher":{"@id":"${SITE_URL}/#person"},"mainEntityOfPage":"${canonical}","image":"${ogImage}"}
    </script>
  </body>
</html>`;

    fs.writeFileSync(path.join(slugDir, "index.html"), html);
    console.log(`Static blog page generated: /blog/${post.slug}`);
  });
}

/** llms-full.txt mein blog section inject karo */
function injectLlmsFullBlog(posts) {
  const llmsPath = path.join(ROOT, "public", "llms-full.txt");
  const existing = fs.readFileSync(llmsPath, "utf8");

  const blogSection = `
## Blog

${posts
  .slice(0, 3)
  .map(
    (p) =>
      `- **${escapeXml(p.title)}** (${new Date(p.date).toLocaleDateString(
        "en-US",
      )}) — ${escapeXml(p.description).substring(0, 150)}...`
  )
  .join("\n")}

---

*Full blog archive at ${SITE_URL}/rss.xml*
`;

  const startMarker = `<!-- LLMS-BLOG:START -->`;
  const endMarker = `<!-- LLMS-BLOG:END -->`;

  if (existing.includes(startMarker) && existing.includes(endMarker)) {
    const re = new RegExp(`${escapeRegex(startMarker)}([\\s\\S]*?)${escapeRegex(endMarker)}`, "m");
    const newContent = existing.replace(re, `${startMarker}\n${blogSection}\n${endMarker}`);
    fs.writeFileSync(llmsPath, newContent);
  } else {
    const newContent = `${existing.trim()}\n${startMarker}\n${blogSection}\n${endMarker}\n`;
    fs.writeFileSync(llmsPath, newContent);
  }
  console.log("llms-full.txt blog section injected");
}

function escapeRegex(string) {
  return string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

const posts = loadPosts();
writePostsModule(posts);
writeRss(posts);
writeSitemap(posts);
injectFaqSchema();
injectBlogSchema(posts);
writeOgImages(posts);
writeStaticBlogPages(posts);
injectLlmsFullBlog(posts);
console.log(`content: ${posts.length} post(s) → posts.gen.js, rss.xml, sitemap.xml, index.html meta, FAQ schema, Blog schema, OG images, static blog, llms-full`);
